### ISSUE TITLE
Layer 4 Right Alt not working for me on High Sierra

### ISSUE THREAD

**Issue by owlJaeger** [jgosmann/neo2-layout-osx#12]
I need the following modification to make it work for me:

![image](https://user-images.githubusercontent.com/62302823/82155294-2e61a180-9874-11ea-9141-dc6f097ff9a2.png)

Maybe you can update the documentation or something. Just wanted to point that fix out.

**Comment by jgosmann** [comment]
What keyboard are you using and which complex modifications did you enable?
It shouldn't be necessary to add that additional modification.

**Comment by owlJaeger** [comment]
I've enabled:
  - `Neo2 layer 4`
  - `Neo2 layer 6`
  - `Neo2 mod 3 and 4 keys (Windows keyboard)`

I am using the `Razer BlackWidow Chroma V2` Keyboard

**Comment by jgosmann** [comment]
I noticed that you are remapping ``right_alt (equal to `right_option`)``. There is also a `right_option` pretty close to the top of the drop down list. How is the behavior if you use `right_option` instead of ``right_alt (equal to `right_option`)`` in the mapping? I suspect that they actually might not be equal (despite it saying so) and you keyboard is sending `right_alt` insteald of `right_option`.

What could also help to understand what is going on: If you disable all modifications, open `karabiner-EventViewer` and look which key code and name you get printed when you use the <kbd>Alt</kbd> and <kbd>Windows</kbd> keys.

**Comment by owlJaeger** [comment]
Using `right_option` for the modification also works for me.
`right_alt (equal to 'right_option')` came from `karabiner-EventViewer` because I've used it to import the key.

Outputs of `karabiner-EventViewer` (without any modifications):
- Left Windows: `227, left_gui`
- Left Alt: `226, left_alt`
- Right Alt Gr: `230, right_alt`

Interestingly, **without** the simple modification but **with** the complex modifications, `right_alt` is interpreted as `right_gui` by `karabiner-EventViewer`

**Comment by jgosmann** [comment]
> Interestingly, **without** the simple modification but **with** the complex modifications, `right_alt` is interpreted as `right_gui` by `karabiner-EventViewer`

And with the simple modification?

**Comment by owlJaeger** [comment]
Interestingly, with the simple modification, nothing is shown by the EventViewer, just like it was never pressed.

**Comment by jgosmann** [comment]
I took another good look at the issue and discovered that I actually hat the same remapping from `right_option` to `right_command` in my simple modifications, but only for my external keyboard (so it wasn't visible unless explicitly selecting that target device). There is also a mapping of `right_option` to `right_command` in the complex rules, that added to the confusion, but it's purpose is that on a Apple keyboard the right option can be used as command (because right command will be mod 4 and there is no need for an additional mod 3/alt).

I think the best course of action here is indeed to amend the documentation with suggested additional mappings for external Windows keyboards, because such simple modifications can be done a a per-device basis (which is not possible with complex modifications and could then make it hard to switch between the internal and external keyboard).

Thank you for providing all that additional information!
